name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4

        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Rodar lint
        run: npm run lint

      - name: Rodar testes
        run: npm run test

      - name: Rodar build
        run: npm run build

      - name: Instalar Vercel CLI
        run: npm install --global vercel

      - name: Fazer deploy
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}